language: python
sudo: required
cache: pip
env:
  REPORT_TO_TRAVIS: 1
  MIN_PYLINT_SCORE: 8
  ARXIV_FEED_CONFIGURATION: Testing
os:
  - linux
python:
  - "3.7"
script:
  - pip install pipenv
  - pipenv sync --dev
  - make test
  - make check
after_success:
  - coveralls
