language: python
sudo: required
cache: pip
env:
  MIN_PYLINT_SCORE: 8
os:
  - linux
python:
  - "3.7"
script:
  - pip install pipenv
  - pipenv sync --dev
  - make test
  - make check-travis
after_success:
  - coveralls
