# Provides the Elasticsearch + Kibana stack for local development. See
# README.md for instructions on use.
---
version: "3.5"
services:
  arxiv-feed-elasticsearch:
    build:
      context: .
      dockerfile: "Dockerfile-elasticsearch"
    container_name: "arxiv-feed-elasticsearch"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "arxiv_feed_network"

  arxiv-feed-kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.4"
    container_name: "arxiv-feed-kibana"
    environment:
      ELASTICSEARCH_URL: "http://arxiv-feed-elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - "arxiv_feed_network"
    depends_on:
      - "arxiv-feed-elasticsearch"

networks:
  arxiv_feed_network:
    name: "arxiv_feed_network"
