# Provides the Elasticsearch + Kibana stack for local development. See
# README.md for instructions on use.
---
version: '3'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    container_name: arxiv-rss-elasticsearch
    environment:    ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports:          ['127.0.0.1:9200:9200', '127.0.0.1:9300:9300']
    networks:       ['es_stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: arxiv-rss-kibana
    # environment:
    #   - ELASTICSEARCH_USERNAME=elastic
    #   - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:          ['127.0.0.1:5601:5601']
    networks:       ['es_stack']
    depends_on:     ['elasticsearch']

networks: {es_stack: {}}
