# Provides the Elasticsearch + Kibana stack for local development. See
# README.md for instructions on use.
---
version: '3'
services:
  arxiv-rss-elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    container_name: arxiv-rss-elasticsearch
    environment:    ['http.host=0.0.0.0', 'transport.host=0.0.0.0']
    ports:          ['9200:9200', '9300:9300']
    networks:       ['arxiv_rss_network']

  arxiv-rss-kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: arxiv-rss-kibana
    # environment:
    #   - ELASTICSEARCH_USERNAME=elastic
    #   - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:          ['127.0.0.1:5601:5601']
    networks:       ['arxiv_rss_network']
    depends_on:     ['arxiv-rss-elasticsearch']

networks: {arxiv_rss_network: {}}
