apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ default "feed" .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "search-api" .Values.deployment.name }}"
    service-group: feed
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
spec:
  replicas: {{ default 1 .Values.scaling.replicas }}
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ default "feed" .Values.deployment.name }}"
        service-group: feed
        log-style: uwsgi
      # annotations:
      #   prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: "{{ default "feed" .Values.deployment.name }}"
        image: arxiv/feed:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: APPLICATION_ROOT
          value: "{{ .Values.ingress.path }}"
        - name: BASE_SERVER
          value: "{{ .Values.base_server }}"
        - name: NAMESPACE
          value: "{{ .Values.namespace }}"
        - name: LOGLEVEL
          value: "{{ default "40" .Values.loglevel }}"
        - name: ELASTICSEARCH_SERVICE_HOST
          value: "{{ default "elasticsearch" .Values.elasticsearch.host }}"
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ default "9200" .Values.elasticsearch.port }}"
        - name: ELASTICSEARCH_SERVICE_PORT_{{ default "9200" .Values.elasticsearch.port }}_PROTO
          value: "{{ default "http" .Values.elasticsearch.proto }}"
        - name: ELASTICSEARCH_INDEX
          value: "{{ default "arxiv" .Values.elasticsearch.index }}"
        - name: ELASTICSEARCH_USER
          value: "{{ default "" .Values.elasticsearch.user }}"
        - name: ELASTICSEARCH_PASSWORD
          value: "{{ default "" .Values.elasticsearch.password }}"
        - name: ELASTICSEARCH_VERIFY
          value: "{{ default "false" .Values.elasticsearch.verify }}"
        - name: CACHE_REDIS_HOST
          value: "{{ default "127.0.0.1" .Values.redis.host }}"
        - name: CACHE_REDIS_PORT
          value: "{{ default "6379" .Values.redis.port }}"
        - name: CACHE_REDIS_DB
          value: "{{ default "0" .Values.redis.db }}"
        - name: FEED_NUM_DAYS
          value: "{{ default "30" .Values.feed.num_days }}"
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
